services:
  backend:
    build: ./apps/backend
    env_file:
      - /home/qemc/Documents/resumeAgentInterface/actions-runner/env/.env
      #- ./apps/backend/.env
    volumes:
      - ${DATA_PATH}:/app/data
      #- ./apps/backend/data:/app/data

  frontend:
    build: ./apps/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
