services:
  backend:
    build: ./apps/backend
    volumes:
      - ${HOST_DB_PATH}:/app/data
    env_file:
      - ./apps/backend/.env

  frontend:
    build: ./apps/frontend
    ports:
      - "80:80"
    depends_on:
      - backend

# docker compose --env-file ./apps/backend/.env up -d
